### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by alan-thomas-shaji** [alan-thomas-shaji/neeto-ui-challenge#8]

**Comment by alan-thomas-shaji** [comment]
Deployed at: https://neetoui-alan-production.herokuapp.com

Can be logged in using:
Username : oliver@example.com
Password: welcome

**Comment by yedhink** [comment]
@alan-thomas-shaji I have provided some reviews for your closed PRs. Once you address and fix them, lemme know over here.

**Comment by alan-thomas-shaji** [comment]
@yedhink: Addressed and fixed the issues mentioned in #15  through #17 

- Removed an unnecessary `div` in Menu.jsx
-  Changed `openMenuBar` in the State hook of index.jsx to `isMenuBarOpen`

**Comment by yedhink** [comment]
@alan-thomas-shaji LGTM. You can mark this task as completed and go ahead with the next one.

**Comment by alan-thomas-shaji** [comment]
Sure, I will do it. Thanks!
